#ifndef MAP_MAPSERVER_PGDBPROCESS_H
#define MAP_MAPSERVER_PGDBPROCESS_H

extern bool LoadDB();
extern HRESULT CALLBACK OnDB_EXECUTE(CEL::DB_RESULT &rkResult);
extern HRESULT CALLBACK OnDB_EXECUTE_TRAN(CEL::DB_RESULT_TRAN &rkResult);

#endif // MAP_MAPSERVER_PGDBPROCESS_H